<?php
$chatbotPageContext = basename($_SERVER['PHP_SELF']);
$chatbotContextValue = isset($chatbotContext) ? (string)$chatbotContext : '';
if ($chatbotContextValue === '' && $chatbotPageContext === 'book.php' && isset($_GET['bookisbn'])) $chatbotContextValue = (string)$_GET['bookisbn'];
?>
<div id="vl-chatbot" class="vl-chatbot" data-context="<?= htmlspecialchars($chatbotContextValue, ENT_QUOTES, 'UTF-8') ?>" data-page="<?= htmlspecialchars($chatbotPageContext, ENT_QUOTES, 'UTF-8') ?>">
  <button type="button" class="vl-chatbot-toggle" aria-label="Mở Trợ lý Việt Long"><i class="fa fa-robot"></i><span>Chat</span></button>
  <section class="vl-chatbot-panel" aria-label="Trợ lý Việt Long" hidden>
    <header class="vl-chatbot-header"><strong><i class="fa fa-robot"></i> Trợ lý Việt Long</strong><button type="button" class="vl-chatbot-close" aria-label="Đóng">×</button></header>
    <div class="vl-chatbot-quick"><button type="button" data-question="Tôi cần biết gì về cửa hàng?">Thông tin cửa hàng</button><button type="button" data-question="Có khuyến mãi nào?">Khuyến mãi</button><button type="button" data-question="Tìm sách giúp tôi">Tìm sản phẩm</button><button type="button" data-question="Đơn hàng của tôi đang ở đâu?">Đơn hàng</button></div>
    <div class="vl-chatbot-messages"><div class="vl-chatbot-message bot">Xin chào! Tôi có thể hỗ trợ về sản phẩm, đơn hàng, khuyến mãi và chính sách.</div></div>
    <form class="vl-chatbot-form"><input type="text" name="message" maxlength="1000" placeholder="Nhập câu hỏi..." autocomplete="off" required><button type="submit" aria-label="Gửi"><i class="fa fa-paper-plane"></i></button></form>
  </section>
</div>
<style>
.vl-chatbot{position:fixed;right:20px;bottom:20px;z-index:1050;font-family:Inter,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}.vl-chatbot-toggle{display:flex;align-items:center;gap:8px;border:0;border-radius:999px;padding:12px 16px;background:#f0b90b;color:#20242b;font-weight:800;box-shadow:0 8px 24px rgba(15,23,42,.2);cursor:pointer}.vl-chatbot-toggle i{font-size:18px}.vl-chatbot-panel{width:350px;height:470px;display:flex;flex-direction:column;overflow:hidden;background:#fff;border:1px solid #e2e8f0;border-radius:14px;box-shadow:0 16px 42px rgba(15,23,42,.22)}.vl-chatbot-header{display:flex;justify-content:space-between;align-items:center;padding:14px 16px;background:#20242b;color:#fff}.vl-chatbot-close{border:0;background:none;color:#fff;font-size:24px;line-height:1;cursor:pointer}.vl-chatbot-quick{display:flex;gap:6px;flex-wrap:wrap;padding:9px 10px;background:#fff;border-bottom:1px solid #e2e8f0}.vl-chatbot-quick button{border:1px solid #dbe2ea;border-radius:999px;background:#fff;color:#475569;padding:5px 8px;font-size:11px;cursor:pointer}.vl-chatbot-quick button:hover{background:#eef2ff;color:#4f46e5}.vl-chatbot-messages{flex:1;overflow-y:auto;padding:14px;background:#f8fafc}.vl-chatbot-message{max-width:88%;margin:0 0 10px;padding:10px 12px;border-radius:11px;white-space:pre-line;font-size:13px;line-height:1.45}.vl-chatbot-message.bot{background:#fff;border:1px solid #e2e8f0;color:#334155}.vl-chatbot-message.user{margin-left:auto;background:#eef2ff;color:#3730a3}.vl-chatbot-message.error{background:#fef2f2;color:#991b1b}.vl-chatbot-form{display:flex;gap:8px;padding:10px;border-top:1px solid #e2e8f0;background:#fff}.vl-chatbot-form input{min-width:0;flex:1;border:1px solid #dbe2ea;border-radius:8px;padding:10px 11px;outline:0}.vl-chatbot-form button{width:42px;border:0;border-radius:8px;background:#4f46e5;color:#fff;cursor:pointer}.vl-chatbot-form button:disabled{opacity:.6}@media(max-width:500px){.vl-chatbot{right:12px;bottom:12px}.vl-chatbot-panel{width:min(350px,calc(100vw - 24px));height:65vh}.vl-chatbot-toggle{padding:11px 13px}.vl-chatbot-toggle span{display:none}}
</style>
<script>
(function(){const root=document.getElementById('vl-chatbot');if(!root)return;const toggle=root.querySelector('.vl-chatbot-toggle'),panel=root.querySelector('.vl-chatbot-panel'),close=root.querySelector('.vl-chatbot-close'),form=root.querySelector('.vl-chatbot-form'),input=form.querySelector('input'),messages=root.querySelector('.vl-chatbot-messages'),quick=root.querySelector('.vl-chatbot-quick');function add(text,type){const el=document.createElement('div');el.className='vl-chatbot-message '+type;el.textContent=text;messages.appendChild(el);messages.scrollTop=messages.scrollHeight;return el}toggle.addEventListener('click',()=>{panel.hidden=false;toggle.hidden=true;input.focus()});close.addEventListener('click',()=>{panel.hidden=true;toggle.hidden=false});quick.addEventListener('click',e=>{const button=e.target.closest('button[data-question]');if(!button)return;input.value=button.dataset.question;form.requestSubmit()});form.addEventListener('submit',async function(e){e.preventDefault();const message=input.value.trim();if(!message)return;add(message,'user');input.value='';input.disabled=true;form.querySelector('button').disabled=true;const loading=add('Đang xử lý...','bot');try{const body=new URLSearchParams({message:message,context:root.dataset.context||root.dataset.page||''});const res=await fetch('chatbot_api.php',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded;charset=UTF-8'},body:body});const data=await res.json();loading.remove();add(data.message||'Không thể xử lý câu hỏi lúc này.',data.success?'bot':'error')}catch(err){loading.textContent='Không thể kết nối chatbot lúc này.';loading.className='vl-chatbot-message error'}finally{input.disabled=false;form.querySelector('button').disabled=false;input.focus()}})})();
</script>
